resources:
  - name: source-code
    type: git
    icon: github
    source:
      uri: git@github.com:m-baaziz/yootchi.git
      branch: main
      private_key: ((git.private_key))

jobs:
  - name: lint
    serial: true
    plan:
      - get: source-code
        trigger: true
      - task: run-lint
        file: source-code/ci/tasks/lint.yml
  - name: test
    serial: true
    plan:
      - get: source-code
        passed: [lint]
        trigger: true
      - task: run-tests
        file: source-code/ci/tasks/test.yml
  - name: staging
    serial: true
    plan:
      - get: source-code
        passed: [test]
        trigger: true
      - task: deploy-staging
        file: source-code/ci/tasks/deploy.yml
        params:
          AWS_ACCESS_KEY_ID: ((aws.yootchi_deploy_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws.yootchi_deploy_secret_access_key))
          AWS_REGION: eu-west-3
          STAGE: staging
  - name: prod
    plan:
      - get: source-code
        passed: [staging]
      - task: deploy-prod
        file: source-code/ci/tasks/deploy.yml
        params:
          AWS_ACCESS_KEY_ID: ((aws.yootchi_deploy_access_key_id))
          AWS_SECRET_ACCESS_KEY: ((aws.yootchi_deploy_secret_access_key))
          AWS_REGION: eu-west-3
          STAGE: prod
